// Generates engine/proof_tables.bend: the invariants used to prove laws L9,
// L10 and L12, and three "check every case" lemmas about them.
//
// Each table lemma says something like "from any valid live set score, after
// one more game the set is still valid". Its proof splits on every small score
// (0-0 up to 6-6, plus "7 or more") and lets Bend compute each case, so every
// leaf is just {==}. Writing those nested case splits by hand would be long and
// error-prone, hence this script. Bend checks the output like any other proof:
// a wrong case fails the check, whoever wrote it.
//
// Run: node prep/gen-proof-tables.ts   (Node 22 runs TypeScript directly)

import { writeFileSync } from "node:fs";

// Nested match on a Nat variable `v` that currently stands for k + v. Cases
// k = 0 .. n-1 get leaf(k); everything from n up gets rest(). Returns lines.
function natMatch(
  v: string,
  k: number,
  n: number,
  leaf: (k: number) => string[],
  rest: () => string[],
): string[] {
  const next = `${v}_${k + 1}`;
  const inner = k + 1 < n ? natMatch(next, k + 1, n, leaf, rest) : rest();
  return [
    `match ${v}:`,
    `  case 0n:`,
    ...leaf(k).map((l) => `    ${l}`),
    `  case 1n+${next}:`,
    ...inner.map((l) => `    ${l}`),
  ];
}

const leaf = (): string[] => ["{==}"];

// Cases over two Nats a and b, each 0 .. n-1 or "n or more".
function grid(a: string, b: string, n: number): string[] {
  return natMatch(a, 0, n, () => natMatch(b, 0, n, leaf, leaf), () => natMatch(b, 0, n, leaf, leaf));
}

function indent(lines: string[], by: number): string[] {
  return lines.map((l) => " ".repeat(by) + l);
}

function casesOver(scrutinees: string, cases: string[], body: string[]): string[] {
  return [
    `  match ${scrutinees}:`,
    ...cases.flatMap((c) => [`    case ${c}:`, ...indent(body, 6)]),
  ];
}

const header = `# proof_tables.bend: invariants and case tables behind laws L9, L10 and L12.
#
# GENERATED by prep/gen-proof-tables.ts. Do not edit by hand; edit the script
# and run: node prep/gen-proof-tables.ts
#
# Bend checks every case below by computation, so a mistake here (in the
# script or the invariants) shows up as a failed proof, not as a wrong result.

import Base
import ./scoring.bend as S
import ./LAWS.bend as Laws

# "p implies q", as a Bool: false only when p is true and q is false.
def Imp(p: Bool, q: Bool) -> Bool:
  Bool.or(Bool.not(p), q)

def IsNone(m: Maybe<S.Side>) -> Bool:
  match m:
    case None{}:
      True{}
    case Some{_}:
      False{}

def BoolEq(p: Bool, q: Bool) -> Bool:
  Bool.not(Bool.xor(p, q))

def PlayTB(play: S.Play) -> Bool:
  match play:
    case S.InGame{_}:
      False{}
    case S.InTiebreak{_}:
      True{}

# ---------------------------------------------------------------------------
# Sets (6 games win a set)
# ---------------------------------------------------------------------------

# A live set is valid when both players have at most 6 games and a tiebreak is
# being played exactly at 6-6.
def LiveOK(+a: Nat, +b: Nat, tb: Bool) -> Bool:
  Bool.and(Nat.is_le(a, 6n), Bool.and(Nat.is_le(b, 6n), BoolEq(tb, Bool.and(Nat.is_eq(a, 6n), Nat.is_eq(b, 6n)))))

# A finished set is valid when its score is an allowed final score (L9).
def FinOK(w: S.Side, +a: Nat, +b: Nat) -> Bool:
  match w:
    case S.A{}:
      Laws.Rule.set_score_ok(a, b)
    case S.B{}:
      Laws.Rule.set_score_ok(b, a)

def SetInv.go(m: Maybe<S.Side>, +a: Nat, +b: Nat, tb: Bool) -> Bool:
  match m:
    case None{}:
      LiveOK(a, b, tb)
    case Some{w}:
      FinOK(w, a, b)

# The set invariant: every set played from 0-0 satisfies it (proven in
# PROOF.bend), and L9 and L10 follow from it.
def SetInv(st: S.TennisSet) -> Bool:
  match st:
    case S.TennisSet{+a, +b, +play}:
      SetInv.go(S.TennisSet.winner(6n, S.TennisSet{a, b, play}), a, b, PlayTB(play))

# Who has won a set at a-b games (it doesn't depend on what is being played).
def W0(+a: Nat, +b: Nat) -> Maybe<S.Side>:
  S.TennisSet.winner(6n, S.TennisSet{a, b, S.InGame{S.Game{0n, 0n}}})

# ---------------------------------------------------------------------------
# Matches (2 sets win a match)
# ---------------------------------------------------------------------------

# Valid set counts: both on at most 1 (live), or one player on exactly 2 with
# the other on at most 1 (finished).
def MInvC(+x: Nat, +y: Nat) -> Bool:
  Bool.or(Bool.and(Nat.is_le(x, 1n), Nat.is_le(y, 1n)), Bool.or(Bool.and(Nat.is_eq(x, 2n), Nat.is_le(y, 1n)), Bool.and(Nat.is_eq(y, 2n), Nat.is_le(x, 1n))))

# The match invariant: every match played from the start satisfies it.
def MatchInv(m: S.Match) -> Bool:
  match m:
    case S.Match{_, +done, _}:
      MInvC(Laws.Rule.sets_won(S.A{}, done), Laws.Rule.sets_won(S.B{}, done))

# Nobody has 2 sets yet.
def MLive(+x: Nat, +y: Nat) -> Bool:
  IsNone(Laws.Rule.pick(Nat.is_ge(x, 2n), Nat.is_ge(y, 2n)))

# The final score L12 asks for, with x as the winner.
def FinM(x: S.Side, +sa: Nat, +sb: Nat) -> Bool:
  match x:
    case S.A{}:
      Bool.and(Nat.is_eq(sa, 2n), Nat.is_le(sb, 1n))
    case S.B{}:
      Bool.and(Nat.is_eq(sb, 2n), Nat.is_le(sa, 1n))

def IsSide(m: Maybe<S.Side>, x: S.Side) -> Bool:
  match m:
    case None{}:
      False{}
    case Some{y}:
      Laws.Rule.same(y, x)
`;

const sides = ["S.A{}", "S.B{}"];
const bools = ["True{}", "False{}"];

// Table 1: from any valid live set score, winning one more game or tiebreak
// leaves a valid set.
const afterOk = [
  "",
  "# From a valid live set at a-b (playing a tiebreak when tb is True), the set",
  "# after a game or tiebreak won by x is valid.",
  "law after_ok:",
  "  for x: S.Side",
  "  for tb: Bool",
  "  for a: Nat",
  "  for b: Nat",
  "  {Imp(Bool.and(LiveOK(a, b, tb), IsNone(W0(a, b))), SetInv(S.TennisSet.add_game(6n, x, a, b))) == True{} : Bool}",
  "",
  "def after_ok(x, tb, a, b):",
  ...casesOver("x tb", sides.flatMap((s) => bools.map((t) => `${s} ${t}`)), grid("a", "b", 7)),
];

// Table 2: from valid live set counts, recording one more set (won by y)
// leaves valid counts.
const setAdded = [
  "",
  "# From valid live set counts sa-sb, one more set won by y leaves valid counts.",
  "law set_added_ok:",
  "  for y: S.Side",
  "  for sa: Nat",
  "  for sb: Nat",
  "  {Imp(Bool.and(MInvC(sa, sb), MLive(sa, sb)), MInvC(Laws.Rule.count(Laws.Rule.same(y, S.A{}), sa), Laws.Rule.count(Laws.Rule.same(y, S.B{}), sb))) == True{} : Bool}",
  "",
  "def set_added_ok(y, sa, sb):",
  ...casesOver("y", sides, grid("sa", "sb", 3)),
];

// Table 3: valid set counts with a winner x have the final score L12 wants.
const matchFinal = [
  "",
  "# Valid set counts with x as the winner give the final score L12 asks for.",
  "law match_final_ok:",
  "  for x: S.Side",
  "  for sa: Nat",
  "  for sb: Nat",
  "  {Imp(Bool.and(MInvC(sa, sb), IsSide(Laws.Rule.pick(Nat.is_ge(sa, 2n), Nat.is_ge(sb, 2n)), x)), FinM(x, sa, sb)) == True{} : Bool}",
  "",
  "def match_final_ok(x, sa, sb):",
  ...casesOver("x", sides, grid("sa", "sb", 3)),
];

const out = header + [...afterOk, ...setAdded, ...matchFinal].join("\n") + "\n";
writeFileSync(new URL("../engine/proof_tables.bend", import.meta.url), out);
console.log(`wrote engine/proof_tables.bend (${out.split("\n").length} lines)`);
