// Generate engine/params.bend from data/players.csv and data/tour.csv.
//
// Run: node prep/params.ts           write engine/params.bend
//      node prep/params.ts --check   only check that it is up to date
//
// If anything is wrong with the inputs (a blank or impossible count, a typed
// SPW/RPW that disagrees with the data, or a point chance outside 0% to 100%
// under either formula), every problem is listed, nothing is written, and the
// exit code is 1. Out-of-range chances are never clamped (law L1).
//
// Each chance in the file is written as Sim.Chance{p, {==}}. The {==} is a
// proof that p is at most 10,000, and Bend checks it when it reads the file,
// so even a bug here can't hand the engine an impossible chance.

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { allChances, type Chances, type Inputs, METHODS, readInputs } from "./model.ts";
import { percent } from "./ratio.ts";

export const PARAMS = "engine/params.bend";

const cap = (m: string) => m.charAt(0).toUpperCase() + m.slice(1);
const sha = (s: string) => createHash("sha256").update(s).digest("hex").slice(0, 16);
const bendString = (s: string) => {
  if (!/^[\x20-\x7e]*$/.test(s) || /["\\]/.test(s)) throw new Error(`can't write ${JSON.stringify(s)} as a Bend string`);
  return `"${s}"`;
};

// The text of params.bend. Same inputs, same text, byte for byte.
export function render(inp: Inputs, ch: Chances, playersText: string, tourText: string): string {
  const ps = inp.players;
  const L: string[] = [];
  const unchecked = ps.filter((p) => !p.checked).length;
  L.push(
    "# params.bend: GENERATED by prep/params.ts from data/players.csv and data/tour.csv.",
    "# Never edit by hand: change the data, then run `node prep/params.ts`.",
    "#",
    `# Players: ${ps.length}, hard courts, ${inp.window.start} to ${inp.window.end}` +
      (unchecked > 0 ? ` (${unchecked} not yet checked by hand)` : ""),
    `# Tour serve average: ${percent(inp.tour, 2)}% of ${inp.tourPoints} serve points in ${inp.tourMatches} matches, ${inp.tourWindow.start} to ${inp.tourWindow.end}`,
    `# Inputs: data/players.csv sha256:${sha(playersText)}, data/tour.csv sha256:${sha(tourText)}`,
    "# Source: Tennis Abstract (Jeff Sackmann), CC BY-NC-SA 4.0.",
    "#",
    "# Every chance is out of 10,000 and written as Sim.Chance{p, {==}}: the {==}",
    "# is a proof that p is at most 10,000, checked by Bend when it reads this",
    "# file (law L1).",
    "",
    "import Base",
    "import ./sim.bend as Sim",
    "",
    "# The players, in the order of data/players.csv.",
    "type Player is Data:",
    ...ps.map((p) => `  ${p.id}{}`),
    "",
    "# The two ways to combine two players' stats (SPEC.md, Point model).",
    "type Method is Data:",
    ...METHODS.map((m) => `  ${cap(m)}{}`),
    "",
    "# Every player, in order.",
    "def Player.all() -> List<&2, Player>:",
    `  [${ps.map((p) => `${p.id}{}`).join(", ")}]`,
    "",
  );
  const table = (name: string, type: string, f: (p: (typeof ps)[number]) => string, comment: string) => {
    L.push(`# ${comment}`, `def Player.${name}(p: Player) -> ${type}:`, "  match p:");
    for (const p of ps) L.push(`    case ${p.id}{}:`, `      ${f(p)}`);
    L.push("");
  };
  table("name", "String", (p) => bendString(p.name), "Her name as Tennis Abstract prints it.");
  table("id", "String", (p) => bendString(p.id), "Her name on the command line: the constructor's name.");
  table("checked", "Bool", (p) => (p.checked ? "True{}" : "False{}"), "Were her RPW and DR checked by hand against her Tennis Abstract page?");
  L.push(
    "def Method.name(m: Method) -> String:",
    "  match m:",
    ...METHODS.flatMap((m) => [`    case ${cap(m)}{}:`, `      ${bendString(m)}`]),
    "",
  );
  for (const m of METHODS) {
    L.push(
      m === "average"
        ? "# Average method: (server's serve share + (1 - receiver's return share)) / 2."
        : "# Additive method: server's serve share + (1 - receiver's return share) - tour serve average.",
      `def Serve.${m}(server: Player, receiver: Player) -> Sim.Chance:`,
      "  match server receiver:",
    );
    ps.forEach((s, i) =>
      ps.forEach((r, j) => L.push(`    case ${s.id}{} ${r.id}{}:`, `      Sim.Chance{${ch[m][i][j]}, {==}}`)),
    );
    L.push("");
  }
  L.push(
    "# The server's chance of winning a point against the receiver.",
    "def Serve.chance(m: Method, server: Player, receiver: Player) -> Sim.Chance:",
    "  match m:",
    ...METHODS.flatMap((m) => [`    case ${cap(m)}{}:`, `      Serve.${m}(server, receiver)`]),
  );
  return L.join("\n") + "\n";
}

// Read the data files and build the text, or return the problems.
export function build(playersText: string, tourText: string): { text: string | null; problems: string[]; inputs: Inputs | null; chances: Chances | null } {
  const { inputs, problems } = readInputs(playersText, tourText);
  if (!inputs) return { text: null, problems, inputs: null, chances: null };
  const r = allChances(inputs);
  if (!r.chances) return { text: null, problems: r.problems, inputs, chances: null };
  return { text: render(inputs, r.chances, playersText, tourText), problems: [], inputs, chances: r.chances };
}

// Run as a script (not when imported by tests or compare.ts).
if (process.argv[1] && resolve(process.argv[1]) === import.meta.filename) {
  const check = process.argv.includes("--check");
  const { text, problems, inputs } = build(readFileSync("data/players.csv", "utf8"), readFileSync("data/tour.csv", "utf8"));
  if (text === null) {
    console.error(`prep: not writing ${PARAMS} (${problems.length} problem${problems.length === 1 ? "" : "s"})`);
    for (const p of problems) console.error(`  ${p}`);
    process.exit(1);
  }
  if (check) {
    let current = "";
    try {
      current = readFileSync(PARAMS, "utf8");
    } catch {}
    if (current !== text) {
      console.error(`${PARAMS} is out of date: run node prep/params.ts`);
      process.exit(1);
    }
    console.log(`${PARAMS} is up to date`);
  } else {
    writeFileSync(PARAMS, text);
    const unchecked = inputs!.players.filter((p) => !p.checked).map((p) => p.name);
    console.log(`Wrote ${PARAMS}: ${inputs!.players.length} players, ${2 * inputs!.players.length ** 2} chances`);
    if (unchecked.length > 0) console.log(`Not yet checked by hand (${unchecked.length}): ${unchecked.join(", ")}`);
  }
}
